<form class="form-horizontal" method="post" action="<?php echo $this->url('galleries/add', array('controlle' => 'Galleries', 'action' => 'add'))?>">
  <div class="control-group">
    <label class="control-label">Name :</label>
    <div class="controls">
      <input type="text" name="galName">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Status :</label>
    <div class="controls">
      <input type="text" name="galStatut">
    </div>
  </div>
    <div class="control-group">
    <label class="control-label">Address :</label>
    <div class="controls">
      <input type="text" name="galAddress">
    </div>
  </div>
    <div class="control-group">
    <label class="control-label">Address 1 :</label>
    <div class="controls">
        <input type="text" name="galAddress1">
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" >Zip Code :</label>
    <div class="controls">
      <input type="text" name="galZipcode">
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" >City :</label>
    <div class="controls">
      <input type="text" name="galCity">
    </div>
  </div>
    <div class="control-group">
    <label class="control-label">Country :</label>
    <div class="controls">
      <input type="text" name="galCountry">
    </div>
  </div>
    <div class="control-group">
    <label class="control-label">Phone Number :</label>
    <div class="controls">
      <input type="text" name="galPhoneNumber">
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" >Email :</label>
    <div class="controls">
      <input type="text" name="galMail">
    </div>
  </div>
    <div class="control-group">
    <label class="control-label">Website :</label>
    <div class="controls">
      <input type="text" name="website">
    </div>
  </div>
    <div class="control-group">
    <label class="control-label">Sur :</label>
    <div class="controls">
      <input type="text" name="sur">
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
        <button type="submit" class="btn">Add <i class="icon-plus"></i></button>
    </div>
  </div>
</form>