<script type="text/javascript">
    var url = 'http://api.twitter.com/1/statuses/user_timeline.json?callback=?'
        +'&screen_name=cnpisit&count=4';

$.getJSON(
    url,
    function (data)
    {
        var $tweets = $('#tweets');
        $tweets.empty();
        if (data.length !== 0) {
            $.each(data, function (i, tweet)
            {
                if (tweet.text !== undefined) {
                    $tweets.append($('<li></li>', { text: tweet.text }));
                }
            });
        } else {
            $tweets.append($('<li></li>', { text: 'No recent tweets' }));
        }
    }
);
</script>

<?php echo"<ul id="."tweets"."><li>Loading tweets...</li></ul>" ?>

<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->title);?></td>
    <td><?php echo $this->escapeHtml($album->artist);?></td>
    <td>
        <a href="<?php echo $this->url('album',
            array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
        <a href="<?php echo $this->url('album',
            array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
<script>
  $(function() {
    $( "#datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      showOn: "button",
      buttonImage: "images/calendar.gif",
      buttonImageOnly: true
    });
    $( "#datepicker1" ).datepicker({
      changeMonth: true,
      changeYear: true,
      showOn: "button",
      buttonImage: "images/calendar.gif",
      buttonImageOnly: true
    });
  });
  </script>
<form>
    <p>Date:<input type="text" id="datepicker" /></p>
    <p>Date:<input type="text" id="datepicker1" /></p>
</form>